import type { Metadata } from "next";
import { Building2, ClipboardCheck, Layers3, Wrench } from "lucide-react";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { ServiceCard } from "@/components/sections/service-card";
import { ServiceCTA } from "@/components/services/service-cta";
import { services } from "@/data/services";

export const metadata: Metadata = { title: "Commercial Property Services", description: "Explore Profix Innovation service options for business and commercial property requirements." };
const requirements = [{ icon: Wrench, title: "Repairs and maintenance", text: "Support options for everyday property issues and maintenance requirements." }, { icon: ClipboardCheck, title: "Planned work", text: "Discuss a planned requirement and the information needed to understand it." }, { icon: Building2, title: "Property issues", text: "Share the context of an issue affecting a business or commercial environment." }, { icon: Layers3, title: "Multiple requirements", text: "Include more than one service need in an enquiry where a property issue crosses categories." }];

export default function CommercialPage() { return <><section className="bg-primary-dark py-16 text-white sm:py-24"><Container><p className="eyebrow text-accent">Commercial property services</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">Professional property maintenance options for business environments.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Our services can support commercial property requirements, subject to the nature and location of the work.</p></Container></section><Section><Container><div className="max-w-2xl"><p className="eyebrow">Service categories</p><h2 className="section-title">A range of property service options</h2></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div></Container></Section><Section tone="muted"><Container><p className="eyebrow">Typical requirements</p><h2 className="section-title">Start with the issue you need to resolve</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{requirements.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-xl border border-border bg-card p-6"><Icon className="size-6 text-primary" aria-hidden="true" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></Container></Section><Section><Container className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">One property, multiple requirements</p><h2 className="section-title">Keep the conversation focused on the property</h2></div><div className="space-y-4 text-lg leading-8 text-muted-foreground"><p>From glazing and locks to plumbing, heating, electrical and pest control, Profix Innovation provides a range of service options in one place.</p><p>Tell us what the property needs and include any useful context. The requirement can then be considered before the next step is discussed.</p></div></Container></Section><ServiceCTA title="Have a commercial property requirement?" description="Tell Profix Innovation what you need and request a quote." primaryLabel="Discuss Your Requirements" /></>; }
