import type { Metadata } from "next";
import Link from "next/link";
import { BriefcaseBusiness, CheckCircle2, MessagesSquare, Wrench } from "lucide-react";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { ServiceCard } from "@/components/sections/service-card";
import { ServiceCTA } from "@/components/services/service-cta";
import { services } from "@/data/services";

export const metadata: Metadata = { title: "About Profix Innovation", description: "Learn about Profix Innovation and its professional property service options for homes and businesses." };
const principles = [{ icon: MessagesSquare, title: "Clear communication", text: "Straightforward conversations about the requirement and the next step." }, { icon: Wrench, title: "Practical solutions", text: "Service options organised around real property maintenance needs." }, { icon: BriefcaseBusiness, title: "Domestic and commercial", text: "A service structure designed for both homes and business properties." }, { icon: CheckCircle2, title: "Customer focus", text: "Useful information and a considered approach from first enquiry." }];

export default function AboutPage() { return <><section className="bg-primary-dark py-16 text-white sm:py-24"><Container><p className="eyebrow text-accent">About Profix Innovation</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">Professional property services for homes and businesses.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">A clear place to explore property maintenance service options and discuss the support your requirement needs.</p></Container></section><Section><Container className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="eyebrow">What we do</p><h2 className="section-title">A practical service network for property requirements</h2></div><div className="space-y-5 text-lg leading-8 text-muted-foreground"><p>Profix Innovation provides property service options covering glazing, locksmith, plumbing, gas and heating, electrical and pest-control requirements.</p><p>The website is designed to make those services easier to understand, whether you are looking after a home, a business or another property setting.</p><Link href="/services" className="inline-flex font-semibold text-primary hover:underline">Explore all services <span aria-hidden="true">→</span></Link></div></Container></Section><Section tone="muted"><Container><p className="eyebrow">Our services</p><h2 className="section-title">One clear place to start</h2><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div></Container></Section><Section><Container><div className="max-w-2xl"><p className="eyebrow">Our approach</p><h2 className="section-title">Professional, clear and focused on the requirement</h2></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{principles.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-xl border border-border bg-card p-6 shadow-[var(--shadow-soft)]"><Icon className="size-6 text-primary" aria-hidden="true" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></Container></Section><ServiceCTA title="Need help with a property requirement?" description="Request a quote from Profix Innovation and tell us what you need." /></>; }
