import Link from "next/link";
import { services, serviceHref } from "@/data/services";
import { siteConfig } from "@/data/site";
import { Container } from "./container";

const usefulLinks = [{ label: "FAQs", href: "/faqs" }, { label: "Advice", href: "/advice" }, { label: "Commercial", href: "/commercial" }, { label: "Areas We Cover", href: "/areas" }, { label: "Request a Quote", href: "/request-a-quote" }];
export function Footer() { return <footer className="border-t border-border bg-slate-950 text-slate-200"><Container className="py-14 sm:py-16"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-5"><div><Link href="/" className="text-lg font-bold tracking-[-0.03em] text-white">Profix <span className="text-sky-300">Innovation</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-slate-400">Professional property maintenance services for homes and businesses.</p></div><FooterColumn title="Company" links={[{ label: "About", href: "/about" }, { label: "Contact", href: "/contact" }]} /><FooterColumn title="Services" links={services.map((service) => ({ label: service.name, href: serviceHref(service) }))} /><FooterColumn title="Explore" links={usefulLinks} /><div><h2 className="text-sm font-semibold text-white">Legal</h2><div className="mt-4 grid gap-2"><FooterLinks links={[{ label: "Privacy Policy", href: "/privacy-policy" }, { label: "Cookie Policy", href: "/cookie-policy" }, { label: "Terms & Conditions", href: "/terms-and-conditions" }]} /></div><h2 className="mt-7 text-sm font-semibold text-white">Contact</h2><a href={`mailto:${siteConfig.contact.email}`} className="mt-4 inline-block break-all text-sm text-sky-300 hover:text-white">{siteConfig.contact.email}</a></div></div><div className="mt-12 flex flex-col gap-3 border-t border-slate-800 pt-6 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} {siteConfig.name}. All rights reserved.</p><p>Information and legal pages should be reviewed before final publication.</p></div></Container></footer>; }
function FooterColumn({ title, links }: { title: string; links: { label: string; href: string }[] }) { return <div><h2 className="text-sm font-semibold text-white">{title}</h2><div className="mt-4 grid gap-2"><FooterLinks links={links} /></div></div>; }
function FooterLinks({ links }: { links: { label: string; href: string }[] }) { return <>{links.map((link) => <Link key={link.href} href={link.href} className="text-sm text-slate-400 transition hover:text-white">{link.label}</Link>)}</>; }
