import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Container } from "@/components/layout/container";
import { advice } from "@/data/advice";
import { getServiceBySlug, serviceHref } from "@/data/services";

export function generateStaticParams() { return advice.map((article) => ({ slug: article.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = advice.find((item) => item.slug === slug); return article ? { title: article.title, description: article.excerpt } : { title: "Advice" }; }
export default async function AdviceArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = advice.find((item) => item.slug === slug); if (!article) notFound(); return <main className="py-12 sm:py-16"><Container className="max-w-3xl"><Link href="/advice" className="text-sm font-semibold text-primary hover:underline">← Back to advice</Link><p className="eyebrow mt-10">{article.category}</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">{article.title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{article.excerpt}</p><article className="mt-10 space-y-6 border-t border-border pt-8 text-base leading-8 text-muted-foreground">{article.content.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</article><div className="mt-10 rounded-2xl bg-muted p-7"><h2 className="text-xl font-bold">Related services</h2><div className="mt-4 flex flex-wrap gap-3">{article.relatedServices.map((slug) => { const service = getServiceBySlug(slug); return service ? <Link key={slug} href={serviceHref(service)} className="font-semibold text-primary hover:underline">{service.name} →</Link> : null; })}</div></div><div className="mt-10 rounded-2xl bg-primary-dark p-7 text-white"><h2 className="text-2xl font-bold">Need help with a property issue?</h2><Link href="/request-a-quote" className="mt-5 inline-flex min-h-11 items-center rounded-[10px] bg-accent px-5 text-sm font-semibold text-accent-foreground">Request a Quote</Link></div></Container></main>; }
