import type { Metadata } from "next";
import Link from "next/link";
import { MapPin, Search } from "lucide-react";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { ServiceCard } from "@/components/sections/service-card";
import { services } from "@/data/services";
import { serviceAreas } from "@/data/areas";

export const metadata: Metadata = { title: "Areas We Cover", description: "Find out whether Profix Innovation can support your property service requirement in your area." };
export default function AreasPage() { return <><section className="bg-primary-dark py-16 text-white sm:py-24"><Container><p className="eyebrow text-accent">Areas we cover</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">Find out whether we provide the service you need in your area.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Our service-area directory is currently being updated. Contact Profix Innovation with your postcode and requirement to discuss availability.</p><Link href="/request-a-quote" className="mt-8 inline-flex min-h-12 items-center rounded-[10px] bg-accent px-6 font-semibold text-accent-foreground">Check Your Area</Link></Container></section><Section><Container>{serviceAreas.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{serviceAreas.filter((area) => area.active).map((area) => <Link key={area.slug} href={`/areas/${area.slug}`} className="rounded-xl border border-border p-6 hover:border-primary"><MapPin className="size-6 text-primary" /><h2 className="mt-4 text-xl font-bold">{area.name}</h2><p className="mt-2 text-sm text-muted-foreground">{area.description}</p></Link>)}</div> : <div className="mx-auto max-w-2xl rounded-2xl border border-border bg-muted p-8 text-center"><Search className="mx-auto size-8 text-primary" aria-hidden="true" /><h2 className="mt-5 text-2xl font-bold">Service-area information is being updated</h2><p className="mt-3 leading-7 text-muted-foreground">Send your postcode and service requirement through the quote form so availability can be discussed.</p><Link href="/request-a-quote" className="mt-6 inline-flex min-h-11 items-center rounded-[10px] bg-primary px-5 text-sm font-semibold text-white">Request a Quote</Link></div>}</Container></Section><Section tone="muted"><Container><p className="eyebrow">Service categories</p><h2 className="section-title">Tell us what your property needs</h2><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div></Container></Section></>; }
