"use client";

import { useEffect, useRef, useState } from "react";

const inputClass = "mt-2 min-h-12 w-full rounded-[10px] border border-border bg-white px-4 text-sm text-foreground outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";

export function ContactForm() {
  const formRef = useRef<HTMLFormElement>(null);
  const errorRef = useRef<HTMLDivElement>(null);
  const [status, setStatus] = useState<{ type: "idle" | "sending" | "success" | "error"; message?: string; reference?: string }>({ type: "idle" });
  useEffect(() => { if (status.type === "error") errorRef.current?.focus(); }, [status.type]);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus({ type: "sending" });
    try { const response = await fetch("/api/enquiries", { method: "POST", body: new FormData(event.currentTarget) }); const result = await response.json() as { ok: boolean; error?: string; reference?: string }; if (!response.ok || !result.ok) throw new Error(result.error || "We couldn't send your enquiry."); setStatus({ type: "success", reference: result.reference }); formRef.current?.reset(); } catch (error) { setStatus({ type: "error", message: error instanceof Error ? error.message : "We couldn't submit your enquiry. Please try again." }); }
  }
  if (status.type === "success") return <div className="rounded-2xl border border-success/20 bg-white p-7 shadow-[var(--shadow-card)]" role="status"><p className="eyebrow text-success">Thank you</p><h2 className="mt-3 text-3xl font-bold">Your message has been received.</h2><p className="mt-4 leading-7 text-muted-foreground">We have received your enquiry. This confirms receipt only and does not confirm an appointment.</p><p className="mt-6 rounded-xl bg-muted p-4 text-sm font-semibold">Reference: <span className="text-primary">{status.reference}</span></p></div>;
  return <form ref={formRef} onSubmit={submit} className="rounded-2xl border border-border bg-white p-5 shadow-[var(--shadow-card)] sm:p-8" noValidate><div className="sr-only" aria-hidden="true"><label htmlFor="contact-website">Website</label><input id="contact-website" name="website" tabIndex={-1} autoComplete="off" /></div><input type="hidden" name="type" value="contact" />{status.type === "error" && <div ref={errorRef} tabIndex={-1} role="alert" className="mb-6 rounded-xl border border-destructive/30 bg-red-50 p-4 text-sm text-destructive">{status.message}</div>}<div className="grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" required autoComplete="name" /><Field label="Email" name="email" type="email" required autoComplete="email" /><Field label="Phone" name="phone" type="tel" autoComplete="tel" /><div><label className="text-sm font-semibold" htmlFor="subject">Subject <span className="text-destructive">*</span></label><select id="subject" name="subject" required className={inputClass}><option value="">Select a subject</option><option value="general">General Enquiry</option><option value="service">Service Enquiry</option><option value="commercial">Commercial Enquiry</option><option value="existing">Existing Enquiry</option><option value="other">Other</option></select></div></div><label className="mt-6 block text-sm font-semibold" htmlFor="message">Message <span className="text-destructive">*</span></label><textarea id="message" name="message" required maxLength={2000} className={`${inputClass} min-h-40 resize-y py-3`} placeholder="How can we help?" /><label className="mt-7 flex items-start gap-3 text-sm leading-6 text-muted-foreground"><input type="checkbox" name="consent" required className="mt-1 size-4 accent-primary" /> <span>By submitting this form, you agree that Profix Innovation may use the information provided to respond to your enquiry.</span></label><button type="submit" disabled={status.type === "sending"} className="mt-7 min-h-12 w-full rounded-[10px] bg-primary px-6 text-sm font-semibold text-white transition hover:-translate-y-px hover:bg-primary/90 disabled:cursor-wait disabled:opacity-60">{status.type === "sending" ? "Sending..." : "Send Message"}</button></form>;
}
function Field({ label, name, required = false, type = "text", ...props }: { label: string; name: string; required?: boolean; type?: string; [key: string]: unknown }) { return <div><label className="text-sm font-semibold" htmlFor={name}>{label} {required && <span className="text-destructive">*</span>}</label><input id={name} name={name} type={type} required={required} className={inputClass} {...props} /></div>; }
